### ISSUE TITLE
make: "nntp/NntpArticle.h:42:25: error: ‘StringFormat’ in ‘class QUuid’ does not name a type"

### ISSUE THREAD

**Issue by sanderjo** [mbruel/ngPost#5]
On Ubuntu 18.04 64-bit, I get the errors belows trying to make.

Tips?

```
sander@brixit:~/git/ngPost/src$ qmake
Info: creating stash file /home/sander/git/ngPost/src/.qmake.stash

sander@brixit:~/git/ngPost/src$ make
/usr/lib/qt5/bin/uic hmi/MainWindow.ui -o ui_MainWindow.h
g++ -c -pipe -O2 -std=gnu++1y -Wall -W -D_REENTRANT -fPIC -DAPP_VERSION="1.6" -D__USE_MUTEX__ -D__DISP_PROGRESS_BAR__ -DQT_NO_DEBUG_OUTPUT -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o NgPost.o NgPost.cpp
In file included from NgPost.cpp:25:0:
nntp/NntpArticle.h:42:25: error: ‘StringFormat’ in ‘class QUuid’ does not name a type
     static const QUuid::StringFormat sMsgIdFormat = QUuid::StringFormat::Id128;
                         ^~~~~~~~~~~~
nntp/NntpArticle.h: In member function ‘QString NntpArticle::id() const’:
nntp/NntpArticle.h:102:55: error: ‘sMsgIdFormat’ was not declared in this scope
 QString NntpArticle::id() const { return _id.toString(sMsgIdFormat); }
                                                       ^~~~~~~~~~~~
nntp/NntpArticle.h:102:55: note: suggested alternative: ‘QTextFormat’
 QString NntpArticle::id() const { return _id.toString(sMsgIdFormat); }
                                                       ^~~~~~~~~~~~
                                                       QTextFormat
Makefile:451: recipe for target 'NgPost.o' failed
make: *** [NgPost.o] Error 1
sander@brixit:~/git/ngPost/src$ 
```

**Comment by AssRap3r** [comment]
same error here on Ubuntu 16.04.6 LTS

*sad face*

**Comment by sanderjo** [comment]
When I go back to tag v1.0.1, I can make.
The next tag (v1.3) and higher breaks it.

**Comment by AssRap3r** [comment]
1.0.1 fails again for me

`NgPost.cpp: In constructor ‘NgPost::NgPost()’:
NgPost.cpp:125:34: error: ‘currentSecsSinceEpoch’ is not a member of ‘QDateTime’
     std::srand(static_cast<uint>(QDateTime::currentSecsSinceEpoch()));
                                  ^
Makefile:361: recipe for target 'NgPost.o' failed
make: *** [NgPost.o] Error 1
`
:<

**Comment by mbruel** [comment]
Hi
Don't use the old version it's quite buggy, you may have some unexpected segfault...

Sor the first issue about QUuid::StringFormat, that's because it was introduced in Qt5.11 and I suppose your Ubuntu ship v5.7 or v5.9... (cf https://doc.qt.io/qt-5/quuid.html#StringFormat-enum)

I've pushed a fix. Please pull and try to compile again.



> 1.0.1 fails again for me
> 
> `NgPost.cpp: In constructor ‘NgPost::NgPost()’: NgPost.cpp:125:34: error: ‘currentSecsSinceEpoch’ is not a member of ‘QDateTime’ std::srand(static_cast<uint>(QDateTime::currentSecsSinceEpoch())); ^ Makefile:361: recipe for target 'NgPost.o' failed make: *** [NgPost.o] Error 1 `
> :<

I can't reproduce that on my env with the latest version and I managed to build with Qt v5.5.1 so I guess you should be good.
Otherwise please let me know your QT version (qmake -v will tell you)

**Comment by AssRap3r** [comment]
Compiles successfully since the update

```
QMake version 3.0
Using Qt version 5.5.1 in /usr/lib/x86_64-linux-gnu
```
one thing I noticed is that the timestamps in the output nzb are off - articles say they're 43830.5d old

**Comment by sanderjo** [comment]
Yes, now works for me too. Thanks!

**Comment by mbruel** [comment]
> one thing I noticed is that the timestamps in the output nzb are off - articles say they're 43830.5d old

could you open a separate ticket plz. I'll look at that in 2020. But the timestamp is supposed to be the time since epoc when you're doing your post.
