### ISSUE TITLE
[Poster #7 {NntpCon #23}] Error SSL Socket: - The peer did not present any certificate 

### ISSUE THREAD

**Issue by tdguchi** [mbruel/ngPost#150]
Hi, im moving from windows 11 to ubuntu 22.04

On windows using ngpost 4.16 worked fine.

But when starting de appimage 4.16 x64 on ubuntu (gui) and trying to post, all worked fine (rar, par2 etc) but when posting, im getting the error in the title.

[Poster #7 {NntpCon #23}] Error SSL Socket: - The peer did not present any certificate 

openssl is installed 

OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)

libssl3 ya está en su versión más reciente (3.0.2-0ubuntu1.6).

Could you give me a clue to fix that please?

Im using newsxs.nl (reader2.newsxs.nl on port 563 with ssl enabled)

thanks!

**Comment by jpoggi** [comment]
Hi,

Waiting for the fix I suggest you to disable TLS.

I have done the same on ubuntu server 22.04.1.

Let's hope a quick fix will pop soon :-)

**Comment by tdguchi** [comment]
> Hi,
> 
> Waiting for the fix I suggest you to disable TLS.
> 
> I have done the same on ubuntu server 22.04.1.
> 
> Let's hope a quick fix will pop soon :-)
> 
> By the way how did you compiled the version and on what os ?

Compile it, i did it and its working with SSL.

**Comment by jpoggi** [comment]
qt5-default is not available on ubuntu 22.04 how did you compile it and on what os ?

**Comment by tdguchi** [comment]
Install these

sudo apt-get install qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools

its the same as installing qt5-default.

**Comment by mbruel** [comment]
@tdguchi yeah it is working with libssl3? I'm surprised...
Otherwise you could maybe install libssll1.1 no?
I'll have a look next week if I can embedded the lib or build an appimage compatible directly

**Comment by tdguchi** [comment]
Yes, its working with these versions.

I cant install libssl1.1 only v3 is offered by repos.

**Comment by jpoggi** [comment]
> Install these
> 
> sudo apt-get install qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools
> 
> its the same as installing qt5-default.

qmake ask for the options when i launch it on ~/ngPost/src

**Comment by tdguchi** [comment]
post the error, so we could see whats going on

**Comment by jpoggi** [comment]
there is no error lol, just the command incomplete it seems:

```
 ~ ngPost/src/master qmake
Usage: /usr/lib/qt5/bin/qmake [mode] [options] [files]

QMake has two modes, one mode for generating project files based on
some heuristics, and the other for generating makefiles. Normally you
shouldn't need to specify a mode, as makefile generation is the default
mode for qmake, but you may use this to test qmake on an existing project

Mode:
  -project       Put qmake into project file generation mode
                 In this mode qmake interprets [files] as files to
                 be added to the .pro file. By default, all files with
                 known source extensions are added.
                 Note: The created .pro file probably will 
                 need to be edited. For example add the QT variable to 
                 specify what modules are required.
  -makefile      Put qmake into makefile generation mode (default)
                 In this mode qmake interprets files as project files to
                 be processed, if skipped qmake will try to find a project
                 file in your current working directory

Warnings Options:
  -Wnone         Turn off all warnings; specific ones may be re-enabled by
                 later -W options
  -Wall          Turn on all warnings
  -Wparser       Turn on parser warnings
  -Wlogic        Turn on logic warnings (on by default)
  -Wdeprecated   Turn on deprecation warnings (on by default)

Options:
   * You can place any variable assignment in options and it will be *
   * processed as if it was in [files]. These assignments will be    *
   * processed before [files] by default.                            *
  -o file        Write output to file
  -d             Increase debug level
  -t templ       Overrides TEMPLATE as templ
  -tp prefix     Overrides TEMPLATE so that prefix is prefixed into the value
  -help          This help
  -v             Version information
  -early         All subsequent variable assignments will be
                 parsed right before default_pre.prf
  -before        All subsequent variable assignments will be
                 parsed right before [files] (the default)
  -after         All subsequent variable assignments will be
                 parsed after [files]
  -late          All subsequent variable assignments will be
                 parsed right after default_post.prf
  -norecursive   Don't do a recursive search
  -recursive     Do a recursive search
  -set <prop> <value> Set persistent property
  -unset <prop>  Unset persistent property
  -query <prop>  Query persistent property. Show all if <prop> is empty.
  -qtconf file   Use file instead of looking for qt.conf
  -cache file    Use file as cache           [makefile mode only]
  -spec spec     Use spec as QMAKESPEC       [makefile mode only]
  -nocache       Don't use a cache file      [makefile mode only]
  -nodepend      Don't generate dependencies [makefile mode only]
  -nomoc         Don't generate moc targets  [makefile mode only]
  -nopwd         Don't look for files in pwd [project mode only]
```

**Comment by tdguchi** [comment]
you are inside master folder, you must change to /src

**Comment by jpoggi** [comment]
nope,

master is the default git branch, ngpost/src is the directory i'm in :-)

**Comment by tdguchi** [comment]
Hmmm, try downloading source from releases page

https://github.com/mbruel/ngPost/releases/tag/v4.16 unzip ( or untar) and try again

**Comment by jpoggi** [comment]
> Hmmm, try downloading source from releases page
> 
> https://github.com/mbruel/ngPost/releases/tag/v4.16 unzip ( or untar) and try again

Cheers mate, it is compiling, i previously just git clone the repo.

**Comment by tdguchi** [comment]
Yeah i know, i have tried to clone it, to bypass your problem, just need to put qmake -project and then make, but it fails on make too... With the zip works fine.

**Comment by tdguchi** [comment]
> I have the same problem using Archlinux and the Appimage :(

Try compiling from source, on this issue you will find steps.


also... @mbruel are you planning on creating a 4.17? with updated libs?

**Comment by Kcchouette** [comment]
I install openssl 1.1 and **it fixes** the problem.

For the compiling thing, I didn't succeed:
```
nntp/NntpArticle.cpp: In constructor ‘NntpArticle::NntpArticle(NntpFile*, uint, qint64, qint64, const std::string*, bool)’:
nntp/NntpArticle.cpp:52:14: error: ‘strcpy’ is not a member of ‘std’; did you mean ‘strcpy’?
   52 |         std::strcpy(_subject, subject.c_str());
      |              ^~~~~~
In file included from /usr/include/qt/QtCore/qarraydata.h:44,
                 from /usr/include/qt/QtCore/qbytearray.h:46,
                 from /usr/include/qt/QtCore/qstring.h:50,
                 from /usr/include/qt/QtCore/quuid.h:43,
                 from /usr/include/qt/QtCore/QUuid:1,
                 from nntp/NntpArticle.h:23,
                 from nntp/NntpArticle.cpp:20:
/usr/include/string.h:141:14: note: ‘strcpy’ declared here
  141 | extern char *strcpy (char *__restrict __dest, const char *__restrict __src)
      |              ^~~~~~
nntp/NntpArticle.cpp: In member function ‘void NntpArticle::yEncBody(const char*)’:
nntp/NntpArticle.cpp:76:10: error: ‘strcpy’ is not a member of ‘std’; did you mean ‘strcpy’?
   76 |     std::strcpy(_body, body.c_str());
      |          ^~~~~~
/usr/include/string.h:141:14: note: ‘strcpy’ declared here
  141 | extern char *strcpy (char *__restrict __dest, const char *__restrict __src)
      |              ^~~~~~
make: *** [Makefile:968: NntpArticle.o] Error 1

```

**Comment by tdguchi** [comment]
> I install openssl 1.1 and **it fixes** the problem.
> 
> For the compiling thing, I didn't succeed:
> 
> ```
> nntp/NntpArticle.cpp: In constructor ‘NntpArticle::NntpArticle(NntpFile*, uint, qint64, qint64, const std::string*, bool)’:
> nntp/NntpArticle.cpp:52:14: error: ‘strcpy’ is not a member of ‘std’; did you mean ‘strcpy’?
>    52 |         std::strcpy(_subject, subject.c_str());
>       |              ^~~~~~
> In file included from /usr/include/qt/QtCore/qarraydata.h:44,
>                  from /usr/include/qt/QtCore/qbytearray.h:46,
>                  from /usr/include/qt/QtCore/qstring.h:50,
>                  from /usr/include/qt/QtCore/quuid.h:43,
>                  from /usr/include/qt/QtCore/QUuid:1,
>                  from nntp/NntpArticle.h:23,
>                  from nntp/NntpArticle.cpp:20:
> /usr/include/string.h:141:14: note: ‘strcpy’ declared here
>   141 | extern char *strcpy (char *__restrict __dest, const char *__restrict __src)
>       |              ^~~~~~
> nntp/NntpArticle.cpp: In member function ‘void NntpArticle::yEncBody(const char*)’:
> nntp/NntpArticle.cpp:76:10: error: ‘strcpy’ is not a member of ‘std’; did you mean ‘strcpy’?
>    76 |     std::strcpy(_body, body.c_str());
>       |          ^~~~~~
> /usr/include/string.h:141:14: note: ‘strcpy’ declared here
>   141 | extern char *strcpy (char *__restrict __dest, const char *__restrict __src)
>       |              ^~~~~~
> make: *** [Makefile:968: NntpArticle.o] Error 1
> ```

Have you cloned the repo?

Try downloading source.tar.gz from releases and compile it, I also had that problem when cloning.

**Comment by kaypoush** [comment]
I had the same strcpy error. Solved it by adding to src/nntp/NntpArticle.cpp `#include <cstring>` in a new line after `#include <sstream>`. Then it compiled successfully and created the executable in the src folder. If you then have a par2 not found error, extract the AppImage (`./ ngPost_v4.16-x86_64.AppImage  --appimage-extract`) from the releases page, edit the .ngPost config file in your home folder and add `PAR2_PATH = /path/to/par2` to it which points to the par2 executable extracted from the AppImage. Worked for me.

**Comment by jpoggi** [comment]
Hi @kaypoush,

I can confirm that this works on Ubuntu 22.04 Server and Ubuntu 23.10 Desktop.

Thanks pal.
